language: java
sudo: false
jdk:
  - oraclejdk8

services:
  - docker

script:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

after_success:
  - mvn clean test jacoco:report coveralls:report
  - if [ "$TRAVIS_BRANCH" == "zeShop/master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push zomzog/cart-service
    docker push zomzog/product-service
    docker push zomzog/auth-service
    docker push zomzog/zuul-gateway
    docker push zomzog/eureka-service
    docker push zomzog/ze-shop-config
    fi