language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "zomzog-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8

services:
  - docker

script:

after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push zomzog/cart-service;
    docker push zomzog/product-service;
    docker push zomzog/auth-service;
    docker push zomzog/zuul-gateway;
    docker push zomzog/eureka-service;
    docker push zomzog/config-service;
    fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'