version: '3'

services:
  configserver:
    image: zomzog/config-service
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always
  discovery:
    image: zomzog/eureka-service
    links:
      - configserver
    depends_on:
      - configserver
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always
  carts:
    image: zomzog/cart-service
    links:
      - configserver
      - discovery
    depends_on:
      - configserver
      - discovery
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always
  products:
    image: zomzog/product-service
    links:
      - configserver
      - discovery
    depends_on:
      - configserver
      - discovery
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always
  auth:
    image: zomzog/auth-service
    links:
      - configserver
      - discovery
    depends_on:
      - configserver
      - discovery
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always
  gateway:
    image: zomzog/gateway-service
    links:
      - configserver
      - discovery
    depends_on:
      - configserver
      - discovery
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx64m
    restart: always