server:
  port: 8040

spring:
    application:
        name: cart-service
    devtools:
        restart:
            enabled: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/zeShopCart;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: zeShop
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: bzh.zomzog.zeshop.util.FixedH2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

liquibase:
    change-log: classpath:config/liquibase/master.xml
    contexts: dev


info:
  id: ${spring.application.name}
  build:
    artifact: ${project.artifactId}
    version: ${project.version}

