
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zomzog/zeShopConfig.git
    devtools:
        restart:
            enabled: true
server:
  port: 8888
