server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zomzog/zeShopConfig.git

zeshop:
  common:
    swagger:
      base-package: bzh.zomzog.zeshop.configuration
      api:
        name: Configuration service
        description: Configuration service API
        version: @project.version@
      contact:
        name: Zomzog
        email: zomzog@zomzog.fr

